WMO_CODES: dict[int, str] = {
  0: "Céu limpo",
  1: "Predom. claro",
  2: "Parcial. nublado",
  3: "Encoberto",
  45: "Nevoeiro",
  48: "Nevoeiro c/ gelo",
  51: "Chuvisco fraco",
  53: "Chuvisco moderado",
  55: "Chuvisco intenso",
  56: "Chuvisco glacial fraco",
  57: "Chuvisco glacial intenso",
  61: "Chuva fraca",
  63: "Chuva moderada",
  65: "Chuva forte",
  66: "Chuva congelante fraca",
  67: "Chuva congelante forte",
  71: "Neve fraca",
  73: "Neve moderada",
  75: "Neve forte",
  77: "Grãos de neve",
  80: "Pancada chuva fraca",
  81: "Pancada chuva moderada",
  82: "Pancada chuva forte",
  85: "Pancada neve fraca",
  86: "Pancada neve forte",
  95: "Tempestade",
  96: "Tempestade c/ granizo fraco",
  99: "Tempestade c/ granizo forte",
}
